# Generated by Django 6.0.4 on 2026-05-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0002_ticket_status_alter_ticket_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="full_name",
        ),
    ]
