# Generated by Django 6.0.4 on 2026-05-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0003_remove_ticket_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="admin_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
