# Generated by Django 6.0.4 on 2026-05-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0005_ticket_priority_alter_ticket_user_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="confidence",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новое"),
                    ("in_progress", "В обработке"),
                    ("done", "Завершено"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
