# Generated by Django 6.0.4 on 2026-05-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0006_ticket_confidence_alter_ticket_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("employee", "Employee"),
                    ("admin", "Admin"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
