# Generated by Django 6.0.4 on 2026-05-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0007_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
